use_frameworks!

platform :ios, '10.0'

target 'EventAgrregatorPrivate_Example' do
  pod 'EventAgrregatorPrivate', :path => '../'

  target 'EventAgrregatorPrivate_Tests' do
    inherit! :search_paths

    
  end
end
