use_frameworks!

platform :ios, '12.0'

target 'EventAgrregatorPrivate_Example' do
  pod 'EventAgrregatorPrivate', :path => '../', :testspecs => ['Tests']

  target 'EventAgrregatorPrivate_Tests' do
    inherit! :search_paths

    
  end
end
